baseURL: 'https://felixvo.github.io/'
languageCode: 'en-us'
title: 'Hi'
theme: 'PaperMod'



enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false
pygmentsUseClasses: true

googleAnalytics: UA-123-45

minify:
    disableXML: true
    minifyOutput: true

params:
    env: production # to enable google analytics, opengraph, twitter-cards and schema.
    title: Hi! I'm Felix
    description: "random stuffs"
    keywords: [Blog, Portfolio, PaperMod]
    author: Me
    # author: ["Me", "You"] # multiple authors
    images: ["<link or path of image for opengraph, twitter-cards>"]
    DateFormat: "January 2, 2006"
    defaultTheme: auto # dark, light
    disableThemeToggle: false

    ShowReadingTime: true
    ShowShareButtons: true
    ShowPostNavLinks: true
    ShowBreadCrumbs: true
    ShowCodeCopyButtons: true
    disableSpecial1stPost: false
    disableScrollToTop: false
    comments: false
    hidemeta: false
    hideSummary: false
    showtoc: false
    tocopen: true


    label:
        text: "~/"
        icon: /apple-touch-icon.png
        iconHeight: 35

    # profile-mode
    profileMode:
        enabled: true # needs to be explicitly set
        title: "I'm Felix, a software engineer"
        subtitle: "Hi there \U0001F44B! Welcome to my space"
        imageUrl: "/profile.jpeg"
        imageWidth: 120
        imageHeight: 120
        imageTitle: felix profile image
        buttons:
            - name: SELECT * FROM posts
              url: posts
            - name: GROUP BY category
              url: categories
  # home-info mode
    homeInfoParams:
        Title: "Hi there \U0001F44B"
        Content: Welcome to my blog

    socialIcons:
        - name: CV
          url: "https://docs.google.com/document/d/1HsoxGCwr70WiN5JV1nXF2AJ1XcvytH9vHoHgK3cgDHg/edit?usp=sharing"
        - name: github
          url: "https://github.com/felixvo"
        - name: stackoverflow
          url: "https://stackoverflow.com/users/7656889/felixvo"

    analytics:
        google:
            SiteVerificationTag: "XYZabc"
        bing:
            SiteVerificationTag: "XYZabc"
        yandex:
            SiteVerificationTag: "XYZabc"

    cover:
        hidden: true # hide everywhere but not in structured data
        hiddenInList: true # hide on list pages and home
        hiddenInSingle: true # hide on single page

    editPost:
        URL: "https://github.com/felixvo/felixvo.github.io/tree/main/content"
        Text: "Suggest Changes" # edit text
        appendFilePath: true # to append file path to Edit link

    # for search
    # https://fusejs.io/api/options.html
    fuseOpts:
        isCaseSensitive: false
        shouldSort: true
        location: 0
        distance: 1000
        threshold: 0.4
        minMatchCharLength: 0
        keys: ["title", "permalink", "summary", "content"]
    ShareButtons: ["linkedin", "twitter", "facebook"]
menu:
    main:
        - identifier: categories
          name: categories
          url: /categories/
          weight: 10
        # - identifier: tags
        #   name: tags
        #   url: /tags/
        #   weight: 20
# Read: https://github.com/adityatelange/hugo-PaperMod/wiki/FAQs#using-hugos-syntax-highlighter-chroma
# pygmentsUseClasses: true
# markup:
#     highlight:
#         # anchorLineNos: true
#         codeFences: true
#         guessSyntax: true
#         lineNos: true
#         style: monokai

